import type { FunctionalComponent, HTMLAttributes, VNodeProps } from 'vue';
declare const MigrationTransferResAwsApplicationDiscoveryServiceMigrationEvaluatorCollector: FunctionalComponent<HTMLAttributes & VNodeProps>;
export default MigrationTransferResAwsApplicationDiscoveryServiceMigrationEvaluatorCollector;
