export { default as FrontEndWebMobileArchAwsAmplify } from './arch-aws-amplify.js'
export { default as FrontEndWebMobileArchAwsDeviceFarm } from './arch-aws-device-farm.js'
export { default as FrontEndWebMobileArchAmazonLocationService } from './arch-amazon-location-service.js'
export { default as FrontEndWebMobileArchCategoryFrontEndWebMobile } from './arch-category-front-end-web-mobile.js'
export { default as FrontEndWebMobileResAwsAmplifyAwsAmplifyStudio } from './res-aws-amplify-aws-amplify-studio.js'
export { default as FrontEndWebMobileResAmazonLocationServiceGeofence } from './res-amazon-location-service-geofence.js'
export { default as FrontEndWebMobileResAmazonLocationServiceMap } from './res-amazon-location-service-map .js'
export { default as FrontEndWebMobileResAmazonLocationServicePlace } from './res-amazon-location-service-place.js'
export { default as FrontEndWebMobileResAmazonLocationServiceRoutes } from './res-amazon-location-service-routes.js'
export { default as FrontEndWebMobileResAmazonLocationServiceTrack } from './res-amazon-location-service-track .js'