import type { FunctionalComponent, HTMLAttributes, VNodeProps } from 'vue';
declare const NetworkingContentDeliveryResAmazonRoute53Route53ApplicationRecoveryController: FunctionalComponent<HTMLAttributes & VNodeProps>;
export default NetworkingContentDeliveryResAmazonRoute53Route53ApplicationRecoveryController;
