import type { FunctionalComponent, HTMLAttributes, VNodeProps } from 'vue';
declare const SecurityIdentityComplianceAwsIdentityAccessManagementLongTermSecurityCredential: FunctionalComponent<HTMLAttributes & VNodeProps>;
export default SecurityIdentityComplianceAwsIdentityAccessManagementLongTermSecurityCredential;
