import type { FunctionalComponent, HTMLAttributes, VNodeProps } from 'vue';
declare const SecurityIdentityComplianceResAwsIdentityAccessManagementTemporarySecurityCredential: FunctionalComponent<HTMLAttributes & VNodeProps>;
export default SecurityIdentityComplianceResAwsIdentityAccessManagementTemporarySecurityCredential;
